### ISSUE TITLE
Could PDK module convert create spec test stubs for existing puppet artifacts?

### ISSUE THREAD

**Issue by salderma** [puppetlabs/pdk-planning#30]
It would be awesome if running `pdk convert` on an existing module would create a spec file for each class/type, etc. detected in the module.  Adding new classes later creates these spec test stubs.

As module development continues, `pdk new` commands like `pdk new class module::my_class` creates spec testing stubs, but there is no way to backfill stubs for existing puppet artifacts in the module.

**Comment by scotje** [comment]
Hi @salderma 

I think this is a great idea, and would be relatively simple for PDK to add new spec files for existing classes that don't have any matching specs.

For this kind of addition we would generally like to see an RFC (request for comments)-style proposal that lays out some specifics of how the feature would work. That level of detail makes it easier to discuss the pros and cons and hammer out an implementation plan. Once accepted, the RFC can also serve as a roadmap for anyone wanting to implement the feature, secure in the knowledge that their PR is likely to be accepted if it implements the RFC as described.

We will certainly add this request to our backlog of potential PDK features, but due to the finite nature of time (*shakes fist at universe*) we can't guarantee if/when this would be implemented. The good news is that anyone can write an RFC and work to implement the feature, so you don't have to wait for us! You can find more information about the process in the README for this repo.

Let me know if you have any other questions!

**Comment by scotje** [comment]
@salderma Good news! This was implemented in PDK 1.14.0! You can now do `pdk convert --add-tests` to have unit tests scaffolded out for existing objects. You can also use `pdk new test --unit` to generate unit tests for individual resources on already converted modules.
